---
- name: Ensure network for cadvisor
  community.docker.docker_network:
    name: cadvisor
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure redis container for cadvisor
  community.docker.docker_container:
    name: cadvisor-redis
    image: redis:latest
    detach: true
    pull: true
    networks:
      - name: cadvisor
    restart_policy: unless-stopped
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create cadvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "{{ cadvisor_ip }}:8080:8080"
    restart_policy: unless-stopped
    detach: true
    pull: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--housekeeping_interval=15s"
      - "--docker_only=true"
    networks:
      - name: cadvisor
  ignore_errors: "{{ ansible_check_mode }}"
